# -*- coding: utf-8 -*-
"""figure_graph_diagrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xw6s1rPGGcRL_bgHdJOVM5JFKasD3gW

# Resultados prévios
"""

import pandas as pd
groups = [
[0.90856,	0.90751,	0.90261,	0.91321,	0.91772,	0.91855,],
[0.91021,	0.90834,	0.90222,	0.91402,	0.91561,	0.91769,],
[0.90799,	0.90868,	0.90264,	0.91312,	0.91707,	0.91732,],
[0.90920,	0.90692,	0.90196,	0.91403,	0.91687,	0.91568,],
[0.90260,	0.90527,	0.90196,	0.91265,	0.91455,	0.91516,],
# [0.70138,	0.73099,	0.71562,	0.65076,	0.53145,	0.63168,],
# [0.74398,	0.70759,	0.70143,	0.61286,	0.55538,	0.61549,],
# [0.61290,	0.72622,	0.69964,	0.47319,	0.43980,	0.64923,],
# [0.61489,	0.72555,	0.69920,	0.46522,	0.43860,	0.64659,],
# [0.61247,	0.72545,	0.69837,	0.45723,	0.44335,	0.65011,],
]


df = pd.DataFrame()
for i, alg in enumerate([
"AVG w/o CLS - Finetune",
"CLS - Finetune",
"First-Last AVG w/o CLS - Finetune",
"AVG - Finetune",
"First Last AVG - Finetune",
# "AVG - Frozen",
# "First Last AVG - Frozen",
# "AVG w/o CLS - Frozen",
# "First Last AVG w/o CLS - Frozen",
# "CLS - Frozen",
]):
    df[alg] = groups[i]
df

import numpy as np
import scipy.stats as stats
import pandas as pd

F_statistic, pVal = stats.f_oneway(*groups)

print ('P value:')
print (pVal,F_statistic)

F_statistic, pVal = stats.f_oneway(*groups)

print ('P value:')
print (pVal,F_statistic)

stacked_data = df.stack().reset_index()
stacked_data = stacked_data.rename(columns={'level_0': 'id',
                                            'level_1': 'treatment',
                                            0:'result'})
print (stacked_data)
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison

# Set up the data for comparison (creates a specialised object)
obj = MultiComparison(
    stacked_data["result"],
    stacked_data["treatment"],
    group_order=[
"AVG w/o CLS - Finetune",
"CLS - Finetune",
"First-Last AVG w/o CLS - Finetune",
"AVG - Finetune",
"First Last AVG - Finetune",
# "AVG - Frozen",
# "First Last AVG - Frozen",
# "AVG w/o CLS - Frozen",
# "First Last AVG w/o CLS - Frozen",
# "CLS - Frozen",
    ],
)
print(obj.groupsunique)
results = obj.tukeyhsd()
print(results)
results.plot_simultaneous(comparison_name='AVG - Finetune',figsize=(6,4))

import pandas as pd
best_model = {
    "ModernBERT - CLS" : [ 0.9734,	0.93992,	0.87474,	0.97794,	0.95818,	0.95403,	0.71882,	0.88469],
    "BERT - F.L. AVG w/o CLS" : [ 0.9696,	0.9134,	0.88425,	0.97862,	0.96748,	0.96069,	0.73552,	0.85985],
    "DistilBERT - F.L. AVG w/o CLS" : [ 0.97040,	0.90115,	0.88395,	0.97766,	0.96589,	0.95528,	0.72120,	0.84558],
    "RoBERTa - AVG" : [ 0.97340,	0.94256,	0.86009,	0.97821,	0.96706,	0.96111,	0.74143,	0.88838],
    "DeBERTa-v3 - F.L. AVG w/o CLS" : [ 0.97420,	0.94723,	0.84768,	0.97880,	0.96316,	0.96403,	0.74999,	0.91148],
    "MPNet - AVG w/o CLS" : [ 0.96800,	0.94228,	0.89175,	0.97839,	0.96737,	0.95569,	0.74422,	0.90065],
}
dfdata = pd.DataFrame(best_model)
dfdata = dfdata*100
dfdata

df = dfdata.T.reset_index()
df.columns = ['Models', "TREC6", "SST2", "SN", "R8", "R52", "OR", "OH", "MR",]
df["num_params"] = [150000000, 110000000, 67000000, 125000000, 184000000, 133000000]

df_long = df.melt(id_vars=['Models', "num_params"],
                  var_name='Dataset',
                  value_name='accuracy')
df_long.columns

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")

sns.scatterplot(
    data=df_long,
    x='num_params',
    y='accuracy',
    hue='Dataset',
    style='Dataset',
    s=100
)

# Adiciona os nomes dos modelos
for _, row in df_long.iterrows():
    plt.text(row['num_params'], row['accuracy'] + 0.00001, row['Models'],
             fontsize=8, ha='center')

plt.xscale('log')
plt.xlabel('Número de Parâmetros')
plt.ylabel('Acurácia')
plt.title('Comparação de Acurácia vs. Parâmetros por Dataset')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Agrupa por modelo
df_avg = df_long.groupby(['Models', 'num_params']).accuracy.mean().reset_index()

plt.figure(figsize=(16, 8))
sns.scatterplot(data=df_avg, x='num_params', y='accuracy',
                hue='Models', style='Models', s=250)

plt.xlabel('Número de Parâmetros', fontsize=16)
plt.ylabel('Acurácia Média(%)', fontsize=16)
# plt.title('Acurácia Média vs. Número de Parâmetros por Modelo')
# plt.xscale('log')
plt.xticks(fontsize=14)
plt.ylim(90, 92)
plt.yticks(fontsize=14)

plt.legend(title='Modelos', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=14, title_fontsize=16)
plt.tight_layout()
plt.show()

df_wide = df_long.pivot(index='Dataset', columns='Models', values='accuracy')
ax = df_wide.T.plot(marker='o', figsize=(10, 6))

plt.xlabel('Models')
plt.ylabel('Accuracy')
# plt.title('Performance of Models by Dataset')
plt.xticks(rotation=45)
plt.tight_layout()

plt.legend(title='Dataset', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_long, x='num_params', y='accuracy',
                hue='Models', style='Dataset', s=140)

plt.xlabel('Number of Parameters', fontsize=17)
plt.ylabel('Accuracy', fontsize=17)
# plt.title('Acurácia vs. Tamanho do Modelo por Dataset')
# plt.xscale('log')
plt.tight_layout()

plt.legend(#title='Models / Dataset',
           bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=15, title_fontsize=17)
plt.savefig('acc_params_dataset.png', dpi=300, bbox_inches='tight')
plt.show()

"""# As análises começam aqui"""

# !wget -O exps.csv https://docs.google.com/spreadsheets/d/1oNht4sqejRUB63i4rjdJr8no4FF_YAWUK6IJe79GLDg/export?format=csv&gid=0
import pandas as pd
df = pd.read_csv('exps.csv')
print(df.embedding.unique())
df.head()

!pip install autorank --quiet

df["domain"].unique()

traducao = {
    "Questions": "Questões",
    "Medical": "Médico",
    "News": "Notícias",
    "Sentiment": "Sentimentos",
    "Law": "Jurídico"
}

df["domain"] = df["domain"].replace(traducao)
df["Domínio"] = df["domain"]

from autorank import autorank, plot_stats, create_report, latex_table
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
from itertools import combinations
import scipy.stats as stats

results_tukey = None
df_local = None

def run_autorank(df):
  alpha = 0.05
  result = autorank(df, alpha=alpha, verbose=False)
  print(result)
  if result.pvalue < alpha:
    plot_stats(result)
    plt.show()
  # print(latex_table(result))
  return result

def box_plot(dataframe, gp1, gp3):
    fontsize_legend = 14
    fontsize_axes = 18
    # Boxplot para domínio e modelo
    plt.figure(figsize=(12, 8))  # aumenta o tamanho da figura

    # sns.boxplot(data=df[df.ft==1].copy(), y=gp1, x='test_acc', hue=gp3,
    sns.boxplot(data=dataframe, y=gp1, x='test_acc', hue=gp3,
                # width=3,
        linewidth=3,        # espessura das linhas do box
        fliersize=6,           # tamanho dos outliers
        dodge=True,              # separa as caixas por grupo
                )
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
            fontsize=fontsize_legend, title_fontsize=12)
    plt.xlabel('Acurácia no Conj. de Teste', fontsize=fontsize_axes)
    plt.ylabel(gp1.capitalize(), fontsize=fontsize_axes)
    plt.xticks(fontsize=fontsize_axes-2)
    plt.yticks(fontsize=fontsize_axes-2)
    plt.tight_layout()
    plt.show()

def get_significatives(df, gp1, gp2, gp3, one_model=False):
  global results_tukey, df_local
  # Exemplo: agrupar por domínio e modelo
  grouped = df.groupby([gp1, gp2])

  # Resultados estatísticos
  results = []

  # for (g1, g2), group in grouped:
  #   emb_acc = group.groupby(gp3)['test_acc'].apply(list)

  #   # Teste t pareado ou ANOVA/Friedman se tiver mais de 2 grupos
  #   g3 = emb_acc.index.tolist()
  #   acc_lists = emb_acc.tolist()

  #   if len(acc_lists) > 1 and all(len(a) == len(acc_lists[0]) for a in acc_lists):  # mesmo número de seeds
  #       if len(acc_lists) == 2:
  #           stat, p = stats.ttest_rel(acc_lists[0], acc_lists[1])
  #           test = 'ttest_rel'
  #       else:
  #           stat, p = stats.friedmanchisquare(*acc_lists)
  #           test = 'friedman'

  #       results.append({
  #           gp1: g1,
  #           gp2: g2,
  #           'test': test,
  #           gp3: g3,
  #           'statistic': stat,
  #           'p_value': p
  #       })
  #       print("="*250)
  #       print("Agrupado por: ", g1, g2, "\nOlhando para: ", gp3)
  #       obj = MultiComparison(
  #       group["test_acc"],
  #       group[gp3])
  #       print(obj.groupsunique)
  #       results_tukey = obj.tukeyhsd()
  #       print(results_tukey)
  #       if sum(results_tukey.pvalues < 0.05) > 0:
  #           i = np.argmin(results_tukey.pvalues)
  #           the_diff = str(results_tukey.summary()[i+1][0])
  #           results_tukey.plot_simultaneous(comparison_name=the_diff,figsize=(6,4));
  #           plt.show()
  #       else:
  #           print("No significative diff in results!")
  # Resultados em DataFrame
  # df_results = pd.DataFrame(results)
  # df_results['significativo'] = df_results['p_value'] < 0.05
  # grouped = df.groupby([
  #     # 'domain',
  #     gp1, gp2, gp3])['test_acc'].mean().reset_index()
  # # Transformando para uma pivot table onde cada linha é domain/model e colunas são embeddings
  # df_local = grouped.pivot(index=[gp1, gp2], columns=gp3, values='test_acc')
  # display(df_local)
  # if one_model:
  #   df_local.index = df_local.index.map('_'.join)
  #   df_local.columns.set_names(None, inplace=True)
  #   df_local.index.set_names('ind', inplace=True)

  # run_autorank(df_local)
#   fontsize_legend = 14
#   fontsize_axes = 18
#   # Boxplot para domínio e modelo
#   sns.violinplot(data=df, y=gp1, x='test_acc', hue=gp3,
#                 # split=True,
#                 inner='quartile'
#                 )
#   plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
#             fontsize=fontsize_legend, title_fontsize=12)
#   plt.xlabel('Test accuracy', fontsize=fontsize_axes)
#   plt.ylabel(gp1.capitalize())
#   plt.show()
  box_plot(df, gp1, gp3)
#   sns.boxplot(data=df, y=gp1, x='test_acc', hue=gp3)
#   plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
#         fontsize=fontsize_legend, title_fontsize=12)
#   plt.xlabel('Test accuracy')
#   plt.ylabel(gp1.capitalize())
#   plt.show()

#   sns.violinplot(data=df, y=gp2, x='test_acc', hue=gp3,
#                 # split=True,
#                 inner='quartile'
#                 )
#   plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
#             fontsize=fontsize_legend, title_fontsize=12)
#   plt.xlabel('Test accuracy')
#   plt.ylabel(gp2.capitalize())
#   plt.show()
  # box_plot(df, gp2, gp3)

#   sns.boxplot(data=df, y=gp2, x='test_acc', hue=gp3)
#   plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
#         fontsize=fontsize_legend, title_fontsize=12)
#   plt.xlabel('Test accuracy')
#   plt.ylabel(gp2.capitalize())
#   plt.show()
  # return df_results

testes = []

"""## Comparando **embeddings**, média por **dataset** agrupando em modelos"""

testes.append(get_significatives(df[df.ft==1].copy(),
                                 'dataset_name', 'model', 'embedding'))
# F.L. sem CLS tem resutlado, o CLS da primeira camada atrapalha

"""## Comparando **embeddings**, média por **domain** agrupando em modelos"""

testes.append(get_significatives(df[df.ft==1].copy(), 'Domínio', 'model', 'embedding'))

"""## Comparando **embeddings**, média por **dataset** agrupando em modelos"""

testes.append(get_significatives(df[df.ft==1].copy(), 'dataset_name', 'model', 'embedding'))

"""## Comparando **modelos**, média por **domain** agrupando em embeddings"""

testes.append(get_significatives(df[df.ft==1].copy(), 'domain', 'embedding', 'model'))
# colocar graph cd no paper

"""## Comparando **modelos**, média por **dataset** agrupando em embeddings"""

testes.append(get_significatives(df[df.ft==1].copy(), 'dataset_name', 'embedding', 'model'))

dfinal = pd.concat(testes).reset_index(drop=True)
print(len(dfinal))
dfinal[dfinal.significativo==1]

dfinal[(dfinal.significativo==1)&(dfinal.dataset_name == 'movie_review')]

"""## Comparando **embeddings**, média por **dataset** agrupando em modelo: **BERT**"""

testes.append(get_significatives(df[(df.ft==1) & (df.model == 'BERT')].copy(), 'dataset_name', 'model', 'embedding', one_model=True))

"""## Comparando **embeddings**, média por **dataset** agrupando em modelo: **DeBERTa**"""

testes.append(get_significatives(df[(df.ft==1) & (df.model == 'DeBERTa-v3')].copy(),
                                 'dataset_name', 'model', 'embedding', one_model=True))

"""## Comparando **embeddings**, média por **dataset** agrupando em modelo: **RoBERTa**"""

testes.append(get_significatives(df[(df.ft==1) & (df.model == 'RoBERTa')].copy(),
                                 'dataset_name', 'model', 'embedding', one_model=True))

"""## Comparando **embeddings**, média por **dataset** agrupando em modelo: **MPNet**"""

testes.append(get_significatives(df[(df.ft==1) & (df.model == 'MPNet')].copy(),
                                 'dataset_name', 'model', 'embedding', one_model=True))

"""## Comparando **embeddings**, média por **dataset** agrupando em modelo: **DistilBERT**"""

testes.append(get_significatives(df[(df.ft==1) & (df.model == 'DistilBERT')].copy(),
                                 'dataset_name', 'model', 'embedding', one_model=True))

"""## Comparando **embeddings**, média por **dataset** agrupando em modelo: **ModernBERT**"""

get_significatives(df[(df.ft==1) & (df.model == 'ModernBERT')].copy(),
                                 'dataset_name', 'model', 'embedding', one_model=True)

"""## Comparando melhores modelos com seus melhores embeddings"""

best_df = df[(df.ft==1)
& (((df.model == 'ModernBERT')&(df.embedding == 'CLS'))
| ((df.model == 'DistilBERT')&(df.embedding == 'F.L.AVG w/o CLS'))
| ((df.model == 'BERT')&(df.embedding == 'F.L.AVG w/o CLS'))
| ((df.model == 'DeBERTa-v3')&(df.embedding == 'F.L.AVG w/o CLS'))
| ((df.model == 'MPNet')&(df.embedding == 'AVG w/o CLS'))
| ((df.model == 'RoBERTa')&(df.embedding == 'AVG')) )
 ].copy().reset_index(drop=True)
best_df

best_df['seed_s'] = best_df.seed.astype(str)

best_df.pivot_table(index=['dataset_name'], columns='model', values='test_acc').mean().T

df_best_model = best_df.pivot_table(index=['dataset_name','seed_s'], columns='model', values='test_acc')
df_best_model.index = df_best_model.index.map('_'.join)
df_best_model.columns.set_names(None, inplace=True)
df_best_model.index.set_names('ind', inplace=True)
run_autorank(df_best_model)
df_best_model

result = autorank(df_best_model, alpha=0.05, verbose=False)
print(result)

"""# Box plot"""

import seaborn as sns
import matplotlib.pyplot as plt

def box_plot(dataframe, gp1, gp3):
    fontsize_legend = 14
    fontsize_axes = 18
    # Boxplot para domínio e modelo
    plt.figure(figsize=(10, 9))  # aumenta o tamanho da figura

    # sns.boxplot(data=df[df.ft==1].copy(), y=gp1, x='test_acc', hue=gp3,
    # sns.boxplot(data=dataframe, y=gp1, x='test_acc', hue=gp3,
    sns.boxplot(data=dataframe, y='test_acc', x=gp1, hue=gp3,
                width=0.8,
        linewidth=1,        # espessura das linhas do box
        fliersize=6,           # tamanho dos outliers
        dodge=True,              # separa as caixas por grupo
                )
    # plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
    #         fontsize=fontsize_legend, title_fontsize=12)
    plt.legend(
    # title="Embedding",
    loc='lower center',
    bbox_to_anchor=(0.5, -0.25),  # ajusta posição abaixo
    ncol=3,                       # divide em 2 colunas
    fontsize=16,
    title_fontsize=18,
    frameon=False
)
    plt.xlabel(gp1.capitalize(), fontsize=fontsize_axes)
    plt.ylabel('Test accuracy', fontsize=fontsize_axes)
    plt.xticks(fontsize=fontsize_axes-2)
    plt.yticks(fontsize=fontsize_axes-2)
    plt.tight_layout()
    plt.savefig("boxplot_export.png", dpi=300, bbox_inches='tight')  # Exporta com qualidade

    plt.show()

# Boxplot para domínio e modelo
# sns.boxplot(data=df[df.ft==1], y='embedding', x='test_acc', hue='dataset_name',
#             )
# plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
#            fontsize=11, title_fontsize=12)
# plt.show()
# box_plot(df[df.ft==1], 'embedding', 'dataset_name')
# box_plot(df[df.ft==1], 'model', 'domain')
dicd = {"overruling": "OR",
        "snippets":"SN",
        "sst2": "SST2",
        "r52": "R52",
        "r8": "R8",
        "movie_review": "MR",
        "Ohsumed": "OH",
        "TREC6": "TREC"}
df['dset'] = df['dataset_name'].replace(dicd)
box_plot(df[df.ft==1], 'model', 'dset')



import seaborn as sns
import matplotlib.pyplot as plt

# Boxplot para domínio e modelo
sns.boxplot(data=df[df.ft==1], y='embedding', x='test_acc', hue='model')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
           fontsize=11, title_fontsize=12)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Boxplot para domínio e modelo
sns.boxplot(data=df[df.ft==1], y='model', x='test_acc', hue='embedding')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
           fontsize=11, title_fontsize=12)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# # Boxplot para domínio e modelo
# sns.boxplot(data=df[df.ft==1], y='model', x='test_acc', hue='domain')
# plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
#            fontsize=11, title_fontsize=12)
# plt.show()
box_plot(df[df.ft==1], 'model', 'domain')

import seaborn as sns
import matplotlib.pyplot as plt

# Boxplot para domínio e modelo
sns.boxplot(data=df[df.ft==1], y='model', x='test_acc', hue='dataset_name')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left',
           fontsize=11, title_fontsize=12)
plt.show()

"""# Testes"""

csv = [line.split(',') for line in """TREC6,BERT,0.9709999999999999,0.9702,0.9693999999999999,0.9708,0.9696
movie_review,BERT,0.861847,0.8608629999999999,0.8633089999999999,0.859455,0.8598480000000001
ohsumed,BERT,0.727432,0.73198,0.735692,0.720356,0.735518
overruling,BERT,0.9536110000000001,0.957639,0.958333,0.9530559999999999,0.960695
r52,BERT,0.967017,0.964837,0.965537,0.9671730000000001,0.9674849999999999
r8,BERT,0.9781190000000001,0.978438,0.978482,0.978027,0.97862
snippets,BERT,0.882325,0.8853949999999999,0.8800000000000001,0.8811389999999999,0.884254
sst2,BERT,0.9140029999999999,0.910763,0.91598,0.9121900000000001,0.9133990000000001""".split("\n")]
cols = "dataset_name,model,AVG FT.,AVG no CLS FT.,CLS FT.,F.L.AVG FT.,F.L.AVG no CLS FT.".split(',')
d = pd.DataFrame(csv, columns=cols)
ncol = d['dataset_name'] + " - " + d['model']
d = d.drop(columns=cols[:2])
d = d.astype(float)
d['ind'] = ncol
d = d.set_index('ind')
display(d)
autorank(d)

df.columns

gp2 = 'dataset_name'
gp1 = 'model'
gp3 = 'embedding'
gp4 = 'domain'
grouped = df[df.ft==1].groupby([
    # 'domain',
    gp4,  gp1, gp3])['test_acc'].mean().round(5).reset_index()
# Transformando para uma pivot table onde cada linha é domain/model e colunas são embeddings
# df_local = grouped.pivot(index=[gp1, gp2], columns=gp3, values='test_acc')
df_local = grouped.groupby([gp4])['test_acc'].apply(list)
df_local

print(df_local.to_dict())

grouped.pivot(index=[gp1, gp4], columns=gp3, values='test_acc')

df[df.ft==1][["model", "domain", "test_acc"]]

grouped

grouped.groupby(["model", "embedding", "domain"])['test_acc'].apply(list).to_dict()

from statsmodels.stats.multicomp import pairwise_tukeyhsd
import pandas as pd

# Suponha que você tenha um DataFrame df com colunas: model, embedding, domain, acc

# Crie uma coluna com a combinação model + embedding
df['group'] = df['model'] + " | " + df['embedding']

# (Opcional) Filtrar por domínio, por exemplo 'news'
df_filtered = df[(df['domain'] == 'news') & (df.ft==1)]  # ou outro domínio

# Aplicar o Tukey HSD
tukey = pairwise_tukeyhsd(endog=df_filtered['test_acc'], groups=df_filtered['group'], alpha=0.05)

# Mostrar resultado
print(tukey.summary())

from statsmodels.stats.multicomp import pairwise_tukeyhsd
import pandas as pd

# Suponha que você tenha um DataFrame df com colunas: model, embedding, domain, acc

# Crie uma coluna com a combinação model + embedding
df['group'] = df['model'] + " | " + df['embedding']

# (Opcional) Filtrar por domínio, por exemplo 'news'
df_filtered = df[(df['domain'] == 'sentiment') & (df.ft==1)]  # ou outro domínio

# Aplicar o Tukey HSD
tukey = pairwise_tukeyhsd(endog=df_filtered['test_acc'], groups=df_filtered['group'], alpha=0.05)

# Mostrar resultado
print(tukey.summary())

df_filtered

"""# Heatmap"""

import pandas as pd
# Organizar os dados em um DataFrame long
model_domain_data = {
    ('BERT', 'Law'): [0.95361, 0.95764, 0.95833, 0.95306, 0.9607],
    ('BERT', 'Medical'): [0.72743, 0.73198, 0.73569, 0.72036, 0.73552],
    ('BERT', 'News'): [0.97257, 0.97164, 0.97201, 0.9726, 0.97305],
    ('BERT', 'Questions'): [0.92666, 0.9278, 0.9247, 0.92597, 0.92693],
    ('BERT', 'Sentiment'): [0.88793, 0.88581, 0.88964, 0.88582, 0.88662],
    ('DeBERTa-v3', 'Law'): [0.96764, 0.96875, 0.9668, 0.96681, 0.96403],
    ('DeBERTa-v3', 'Medical'): [0.74695, 0.74289, 0.74452, 0.7461, 0.74999],
    ('DeBERTa-v3', 'News'): [0.96989, 0.97121, 0.96929, 0.96791, 0.97098],
    ('DeBERTa-v3', 'Questions'): [0.91153, 0.9169, 0.90973, 0.90717, 0.91094],
    ('DeBERTa-v3', 'Sentiment'): [0.92879, 0.92697, 0.92777, 0.92667, 0.92935],
    ('DistilBERT', 'Law'): [0.95431, 0.955, 0.95583, 0.95361, 0.95528],
    ('DistilBERT', 'Medical'): [0.71177, 0.7186, 0.71719, 0.71301, 0.7212],
    ('DistilBERT', 'News'): [0.97096, 0.97101, 0.9707, 0.9706, 0.97177],
    ('DistilBERT', 'Questions'): [0.92851, 0.92829, 0.92816, 0.92988, 0.92717],
    ('DistilBERT', 'Sentiment'): [0.87536, 0.87435, 0.87351, 0.87406, 0.87337],
    ('MPNet', 'Law'): [0.95278, 0.95569, 0.95514, 0.9525, 0.95361],
    ('MPNet', 'Medical'): [0.73292, 0.74422, 0.74019, 0.7352, 0.73846],
    ('MPNet', 'News'): [0.97321, 0.97288, 0.97417, 0.96838, 0.97403],
    ('MPNet', 'Questions'): [0.92982, 0.92988, 0.92948, 0.93, 0.92877],
    ('MPNet', 'Sentiment'): [0.91686, 0.92147, 0.91946, 0.91843, 0.92044],
    ('ModernBERT', 'Law'): [0.95264, 0.95028, 0.95403, 0.9425, 0.94805],
    ('ModernBERT', 'Medical'): [0.71625, 0.72021, 0.71882, 0.69743, 0.70942],
    ('ModernBERT', 'News'): [0.96938, 0.96781, 0.96806, 0.96481, 0.96815],
    ('ModernBERT', 'Questions'): [0.92154, 0.92166, 0.92407, 0.91711, 0.92348],
    ('ModernBERT', 'Sentiment'): [0.91141, 0.90954, 0.91231, 0.90852, 0.9116],
    ('RoBERTa', 'Law'): [0.96111, 0.95834, 0.96014, 0.95903, 0.95986],
    ('RoBERTa', 'Medical'): [0.74143, 0.7437, 0.74586, 0.74113, 0.74445],
    ('RoBERTa', 'News'): [0.97263, 0.97363, 0.97224, 0.9734, 0.97174],
    ('RoBERTa', 'Questions'): [0.91674, 0.91251, 0.91624, 0.91447, 0.91559],
    ('RoBERTa', 'Sentiment'): [0.91547, 0.91568, 0.91458, 0.91266, 0.91298],
}

# Converter para DataFrame
model_domain_df = pd.DataFrame([
    (model, domain, acc)
    for (model, domain), accs in model_domain_data.items()
    for acc in accs
], columns=["model", "domain", "acc"])

# ANOVA de dois fatores com interação
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Ajustar modelo de ANOVA com interação
anova_model = ols('acc ~ C(model) * C(domain)', data=model_domain_df).fit()
anova_table = sm.stats.anova_lm(anova_model, typ=2)
anova_table

import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Calcular médias de acurácia por model x domain para o heatmap
heatmap_data = model_domain_df.groupby(['domain', 'model'])['acc'].mean().unstack()

# Gerar heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(heatmap_data, annot=True, fmt=".3f", cmap="viridis", cbar_kws={'label': 'Mean Acc'})
# plt.title("Heatmap de Acurácia Média por Modelo e Domínio")
plt.ylabel("Domain")
plt.xlabel("Model")
plt.tight_layout()
plt.show()

"""# Dendograma"""

import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram
import seaborn as sns

# Agrupar por embedding_type, domain e dataset_name, e tirar média da acurácia
grouped = df.groupby(['embedding_type', 'domain', 'dataset_name'])['test_acc'].mean().reset_index()

# Criar uma identificação hierárquica para rotulagem
grouped['label'] = grouped['embedding_type'] + ' | ' + grouped['domain'] + ' | ' + grouped['dataset_name']

pivot_df = grouped.pivot(index='label', columns='embedding_type', values='test_acc').fillna(0)

# Calcular linkage para clustering hierárquico
Z = linkage(pivot_df, method='ward')

# Plotar o dendrograma
plt.figure(figsize=(12, 8))
dendrogram(Z, labels=pivot_df.index, leaf_rotation=90, leaf_font_size=8)
plt.title("Dendrograma Hierárquico por Embedding → Domínio → Dataset")
plt.xlabel("Combinação")
plt.ylabel("Distância")
plt.tight_layout()
plt.show()